apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-agent-config
data:
  agent.yaml: |
    server:
      log_level: info
      http_listen_port: 12345

    prometheus:
      wal_directory: /tmp/grafana-agent-wal
      global:
        scrape_interval: 15s
        evaluation_interval: 15s
      configs:
        - name: integrations
          scrape_configs:
            - job_name: 'prometheus'
              static_configs:
                - targets: ['localhost:9090']

    server:
      http_listen_port: 3100
      http_listen_address: "0.0.0.0"
    
    loki:
      positions_directory: /tmp/positions
      clients:
        - url: http://loki:3100/loki/api/v1/push

      scrape_configs:
        - job_name: varlogs
          static_configs:
            - targets:
                - localhost
              labels:
                job: varlogs
                __path__: /var/log/*log
