# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hivebox-scalable-restful-api-for-beekeepers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hivebox-scalable-restful-api-for-beekeepers
  template:
    metadata:
      labels:
        app: hivebox-scalable-restful-api-for-beekeepers
    spec:
      containers:
        - name: hivebox-scalable-restful-api-for-beekeepers
          image: ahmedgamalyousef/hivebox-scalable-restful-api-for-beekeepers:latest
          ports:
            - containerPort: 80
          env:
            - name: SENSEBOX_IDS
              value: "5eba5fbad46fb8001b799786"
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
            - name: MINIO_ENDPOINT
              value: "minio:9000"
            - name: MINIO_ACCESS_KEY
              value: "minioadmin"
            - name: MINIO_SECRET_KEY
              value: "minioadmin"
            - name: MINIO_BUCKET
              value: "mybucket"
          readinessProbe:
            httpGet:
              path: /readyz
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
