# ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fhivebox-scalable-restful-api-for-beekeepers-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: www.jemy.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hivebox-scalable-restful-api-for-beekeepers
                port:
                  number: 80
