apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sensebox-ingress
spec:
  rules:
    - host: sensebox.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sensebox-service
                port:
                  number: 80
