apiVersion: v1
kind: Service
metadata:
  name: grafana-agent
  namespace: default
spec:
  selector:
    app: grafana-agent
  ports:
    - protocol: TCP
      port: 12345
      targetPort: 12345
  type: ClusterIP
