apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hivebox-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/JemyYousef/HiveBox-Scalable-RESTFUL-API-For-Beekeepers'
    targetRevision: HEAD
    path: 'path/to/your/k8s/manifests'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
