name: CD Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract version number
      id: vars
      run: echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV

    - name: Build and Push Docker image
      run: |
        docker build -t ghcr.io/${{ github.repository }}/my-flask-app:${{ env.VERSION }} .
        docker push ghcr.io/${{ github.repository }}/my-flask-app:${{ env.VERSION }}

    - name: Tag Docker image as latest
      run: |
        docker tag ghcr.io/${{ github.repository }}/my-flask-app:${{ env.VERSION }} ghcr.io/${{ github.repository }}/my-flask-app:latest
        docker push ghcr.io/${{ github.repository }}/my-flask-app:latest
