name: CI/CD Workflow

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        pip install -r requirements.txt

    - name: Lint code
      run: flake8 .

    - name: Lint Dockerfile
      run: |
        curl -fsSL https://github.com/hadolint/hadolint/releases/download/v1.17.3/hadolint-Linux-x86_64 -o hadolint
        chmod +x hadolint
        ./hadolint Dockerfile

###########################################################

  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t ahmedgamalyousef/hivebox2:latest .
    
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Install KIND
      run: |
        curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.11.1/kind-linux-amd64
        chmod +x ./kind
        sudo mv ./kind /usr/local/bin/kind

    - name: Create KIND cluster
      run: kind create cluster --config kind-config.yaml

    - name: Deploy Application
      run: |
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml

    # - name: Wait for Deployment
    #   run: |
    #     kubectl wait --for=condition=available --timeout=300s deployment/hivebox-scalable-restful-api-for-beekeepers
    - name: Install Venom
      run: |
        curl -LO https://github.com/ovh/venom/releases/download/v1.0.0/venom-linux-amd64
        chmod +x venom-linux-amd64
        sudo mv venom-linux-amd64 /usr/local/bin/venom

    - name: Run Venom Tests
      run: venom run venom_test.yaml

###########################################################

  test:
    runs-on: ubuntu-latest
    needs: build
    services:
      redis:
        image: redis:latest
        options: --privileged
        ports:
          - 6379:6379
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Start Flask App
      run: nohup python app.py &

    - name: wait for the server to start
      run: sleep 10 

    - name: Run integration tests
      run: |
        python -m pytest 
        
###########################################################

  sonarqube:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Ensure Shell Availability
      run: |
        sudo apt-get update
        sudo apt-get install -y dash bash
        if [ ! -L /bin/sh ]; then sudo ln -sf /bin/dash /bin/sh; fi  # Force link sh to dash

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Verify Java Installation
      run: |
        ls -l /usr/lib/jvm/
        ls -l /usr/lib/jvm/temurin-17-jdk-amd64/bin/

    - name: Verify Java Version
      run: |
        /usr/lib/jvm/temurin-17-jdk-amd64/bin/java -version

    - name: Verify Java Version
      run: java -version
     
    - name: Install SonarScanner
      run: |
        sudo apt-get update
        sudo apt-get install -y unzip
        curl -sSLo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
        unzip sonar-scanner.zip
        export SONAR_SCANNER_HOME=$(pwd)/sonar-scanner-4.6.2.2472-linux
        echo "SONAR_SCANNER_HOME=$SONAR_SCANNER_HOME" >> $GITHUB_ENV
        echo "PATH=$SONAR_SCANNER_HOME/bin:\$PATH" >> $GITHUB_ENV
        source $GITHUB_ENV  # Apply the environment variable
        echo "SonarScanner home is set to: $SONAR_SCANNER_HOME"
        ls -l $SONAR_SCANNER_HOME/bin  # Verify the sonar-scanner directory
    
    # - name: Debug PATH
    #   run: |
    #       echo "Current PATH: $PATH"
    #       which sonar-scanner
    #       ls -l $SONAR_SCANNER_HOME/bin      
    
    # - name: Verify SonarScanner Installation
    #   run: |
    #       sonar-scanner --version  # Verify SonarScanner is correctly installed
    
    # - name: Run SonarQube Scan
    #   shell: /bin/bash
    #   env:
    #     JAVA_HOME: /usr/lib/jvm/temurin-17-jdk-amd64
    #     # SONAR_SCANNER_HOME: /home/runner/work/HiveBox-Scalable-RESTful-API-for-Beekeepers/HiveBox-Scalable-RESTful-API-for-Beekeepers/sonar-scanner-4.6.2.2472-linux
    #     PATH: $SONAR_SCANNER_HOME/bin:/usr/lib/jvm/temurin-17-jdk-amd64/bin:$PATH
    #   run: |
    #     sonar-scanner \
    #     -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }} \
    #     -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }} \
    #     -Dsonar.host.url=https://sonarcloud.io \
    #     -Dsonar.login=${{ secrets.SONAR_TOKEN }}   

###########################################################

  terrascan:
    runs-on: ubuntu-latest
    needs: sonarqube
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Terrascan
      run: |
        curl -sSLo terrascan.tar.gz https://github.com/tenable/terrascan/releases/download/v1.12.0/terrascan_1.12.0_Linux_x86_64.tar.gz
        tar -xzvf terrascan.tar.gz
        sudo mv terrascan /usr/local/bin/
        terrascan version

    # - name: Run Terrascan
    #   uses: accurics/terrascan-action@v1
    #   with:
    #     iac_dir: "."
    #     iac_type: "k8s"
    #     policy_type: "all"
    #     verbose: true

###########################################################

  push_image:
    runs-on: ubuntu-latest
    needs: terrascan
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker Image
      run: docker build -t ahmedgamalyousef/hivebox-scalable-restful-api-for-beekeepers:latest .
        
    - name: Push Docker Image
      run: docker push ahmedgamalyousef/hivebox-scalable-restful-api-for-beekeepers:latest 