name: CI Workflow

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        pip install -r requirements.txt

    - name: Lint code
      run: flake8 .

    - name: Lint Dockerfile
      run: |
        curl -fsSL https://github.com/hadolint/hadolint/releases/download/v1.17.3/hadolint-Linux-x86_64 -o hadolint
        chmod +x hadolint
        ./hadolint Dockerfile

  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t my-app:latest .

  test:
    runs-on: ubuntu-latest
    needs: build
    services:
      docker:
        image: my-app:latest
        options: --privileged
        ports:
          - 5000:5000
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run unit tests
      run: |
        docker ps
        curl http://localhost:5000/version

  scorecard:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run OpenSSF Scorecard
      uses: ossf/scorecard-action@v2.4.0
      with:
        results_file: results.sarif
        results_format: sarif
    